### ISSUE TITLE
Review existing code base

### ISSUE THREAD

**Issue by davidbrownza** [davidbrownza/CORMAP#14]
Review and profile existing code base. A number of new issues could come from this review.

**Comment by davidbrownza** [comment]
#### Proposed directory structure

```
src/
    conn/
        DBConnection.h
        DBConnection.cpp
    fields/
        IField.h // proposed new "interface" class
        Field.h
        IntegerField.cpp
        FloatField.cpp
        TextField.cpp
        CharField.cpp
        BooleanField.cpp
    model/
        Model.h
        Model.cpp
    schema/ // proposed new classes to handle DB schema operations
        Schema.h
        Schema.cpp
tst/
    unit/ // directory where unit tests will live
    compile_test.sh
    test.cpp
```

**Comment by davidbrownza** [comment]
Based on recent CRs, the code guidelines need to change as follows:
1. all private member variables get an underscore in front of them (someone using this class can't access those variables directly anyway, so I would rather they were ugly than the method parameters).
1. We avoid use of `this->` and `this.`
1. We make the method signatures as pretty as possible, meaning full length words and consistency throughout.

**Comment by rowan08** [comment]
Additionally, for consistency, we need to maintain the following:

1. All files end on a new line.
2. We keep a blank line open between methods
3. The use curly braces as follows:
```
if (condition) {
         ...
}
```
4. We include a space before opening parentheses or curly braces
 e.g. between `if` and `(`, `)` and `{`, etc

**Comment by davidbrownza** [comment]
Updated #34 with details from this investigation.
